language: node_js
node_js:
  - 8.3.0
cache:
  directories:
    - node_modules

script:
  - npm run build

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "cdn.tanachstudy.com"
    skip_cleanup: true
    region: us-east-1
    local_dir: dist/bundle
    upload-dir: travis-dist
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "tanachstudy.com"
    skip_cleanup: true
    region: us-east-1
    local_dir: dist/html
    upload-dir: travis-dist
