language: node_js
node_js:
  - 8.3.0
cache:
  directories:
    - node_modules
install:
  - npm install
  - sudo pip install awscli
script:
  - npm run build
deploy:
  - provider: script
    script: npm run deploy
    skip_cleanup: true
    on:
      branch: master
