language: node_js
node_js:
  - 8.3.0
cache:
  directories:
    - node_modules
env:
  - DB_CONNECTION=$DB_CONNECTION
install:
  - npm install
script:
  - npm run build
deploy:
  - provider: script
    script: npm run deploy
    skip_cleanup: true
    on:
      branch: master
